# Generated by Django 6.0.2 on 2026-02-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_group_groupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
