# Generated by Django 6.0.2 on 2026-03-04 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_apitoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Lab Incharge')], db_index=True, default='student', max_length=20),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['status', 'created_at'], name='group_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['faculty', 'status', 'created_at'], name='group_fac_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group', 'role'], name='groupmember_group_role_idx'),
        ),
        migrations.AddIndex(
            model_name='groupremovalrequest',
            index=models.Index(fields=['group', 'status', 'created_at'], name='grprem_grp_stat_created_idx'),
        ),
    ]
