# Generated by Django 6.0.2 on 2026-03-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_group_id_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(
                choices=[
                    ('SIGNUP', 'Signup'),
                    ('PASSWORD_RESET', 'Password Reset'),
                    ('ADMIN_EMAIL_CHANGE', 'Admin Email Change'),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
