# Generated by Django 6.0.2 on 2026-03-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_email_locked_and_emailotp_admin_email_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='batch_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='program',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
