# Generated by Django 6.0.2 on 2026-03-16

import datetime
from django.db import migrations, models
from django.utils import timezone


def set_initial_expiry(apps, schema_editor):
    APIToken = apps.get_model("users", "APIToken")
    default_expiry = timezone.now() + datetime.timedelta(days=30)
    APIToken.objects.filter(expires_at__isnull=True).update(expires_at=default_expiry)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_profile_batch_year_profile_branch_profile_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True, db_index=True),
        ),
        migrations.RunPython(set_initial_expiry, migrations.RunPython.noop),
    ]
