# Generated by Django 6.0.2 on 2026-02-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('TERMINATED', 'Terminated'), ('RETURNED', 'Returned')], default='PENDING', max_length=20),
        ),
    ]
