# Generated by Django 6.0.2 on 2026-02-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0005_set_group_and_due_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='return_condition',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
