# Generated by Django 6.0.2 on 2026-02-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0006_borrowrequest_return_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
