# Generated by Django 6.0.2 on 2026-02-28 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_component_available_stock_and_more'),
        ('requests_app', '0007_borrowrequest_return_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrequest',
            name='counsellor',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='group',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='student',
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='counsellor_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='faculty_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ISSUED', 'Issued'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='BorrowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('borrow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requests_app.borrowrequest')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_items', to='inventory.component')),
            ],
        ),
        migrations.DeleteModel(
            name='BorrowRequestItem',
        ),
    ]
