# Generated by Django 6.0.2 on 2026-02-28 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0009_faculty_fk_actions_user_not_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowaction',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ISSUED', 'Issued'), ('RETURNED', 'Returned'), ('PENALTY', 'Penalty'), ('AUTO_OVERDUE', 'Auto Overdue')], max_length=20),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='faculty',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'faculty'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faculty_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ISSUED', 'Issued'), ('RETURNED', 'Returned'), ('PENALTY', 'Penalty'), ('OVERDUE', 'Overdue')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
