# Generated by Django 6.0.2 on 2026-03-01 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0010_alter_borrowaction_action_and_more'),
        ('users', '0006_seed_lab_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_requests', to='users.group'),
        ),
    ]
