# Generated by Django 6.0.2 on 2026-03-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0011_borrowrequest_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='cart_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
