# Generated by Django 6.0.2 on 2026-03-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0012_borrowrequest_cart_locked_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_day_fine', models.PositiveIntegerField(default=10)),
                ('grace_days', models.PositiveIntegerField(default=2)),
                ('overdue_penalty_trigger_days', models.PositiveIntegerField(default=5)),
                ('damaged_fine', models.PositiveIntegerField(default=500)),
                ('missing_parts_fine', models.PositiveIntegerField(default=700)),
                ('not_working_fine', models.PositiveIntegerField(default=1000)),
                ('maintenance_keywords', models.CharField(default='service,damaged,not working,missing', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='borrowaction',
            options={},
        ),
    ]
