# Generated by Django 6.0.2 on 2026-03-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0013_labpolicy_alter_borrowaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowaction',
            options={'ordering': ['-timestamp']},
        ),
    ]
