# Generated by Django 6.0.2 on 2026-03-04 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_reservation_unique_together_and_more'),
        ('requests_app', '0014_alter_borrowaction_options'),
        ('users', '0011_alter_profile_group_id_alter_profile_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='borrowaction',
            index=models.Index(fields=['borrow_request', 'timestamp'], name='borrowaction_req_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowaction',
            index=models.Index(fields=['action', 'timestamp'], name='borrowaction_action_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowitem',
            index=models.Index(fields=['borrow_request', 'component'], name='borrowitem_req_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['faculty', 'status', 'created_at'], name='brreq_fac_stat_created_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['group', 'status', 'created_at'], name='brreq_grp_stat_created_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['status', 'due_date'], name='borrowreq_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['status', 'reminder_sent', 'due_date'], name='borrowreq_status_rem_due_idx'),
        ),
    ]
