# Generated by Django 6.0.2 on 2026-02-22 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='component',
            name='available_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='component',
            name='total_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('student', 'component')},
        ),
    ]
