# Generated by Django 6.0.2 on 2026-02-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_component_category_alter_cartitem_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='faculty_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='component',
            name='student_limit',
            field=models.IntegerField(default=0),
        ),
    ]
