# Generated by Django 6.0.2 on 2026-03-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_reservation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='fine_damaged',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='fine_missing_parts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='fine_not_working',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='fine_per_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
